ALTER TABLE `users` ADD `uuid` CHAR(36) NULL DEFAULT NULL AFTER `id`, ADD UNIQUE (`uuid`);
ALTER TABLE `users` CHANGE `tel` `tel` BIGINT(14) UNSIGNED NULL DEFAULT NULL;
ALTER TABLE `users` CHANGE `password` `password` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
